# Form implementation generated from reading ui file 'addItemUi.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class AddItem_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.screen = QtWidgets.QApplication.primaryScreen()
        self.screen_geometry = self.screen.geometry()
        self.screen_width = self.screen_geometry.width()
        self.screen_height = self.screen_geometry.height()
        Form.resize(self.screen_width, self.screen_height)
        Form.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(5, 5, 581, 531))
        self.widget.setStyleSheet("QPushButton#okButton{\n"
"    background-color:#984063;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#okButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#26648E;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#okButton:hover{\n"
"    background-color:#26648E;\n"
"}\n"
"QPushButton#cancelButton{\n"
"    background-color:#984063;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#cancelButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#26648E;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#cancelButton:hover{\n"
"    background-color:#26648E;\n"
"}\n"
"QComboBox {\n"
"            border: 1px solid #984063;\n"
"            border-radius: 5px;\n"
"            padding-left: 4px;\n"
"            padding-right: 8px; \n"
"        }\n"
"        QComboBox::drop-down {\n"
"            subcontrol-origin: padding;\n"
"            subcontrol-position: top right;\n"
"            width: 25px;\n"
"            border-left: 1px solid #984063;\n"
"            border-top-right-radius: 5px;\n"
"            border-bottom-right-radius: 5px;\n"
"            background: #984063;\n"
"        }\n"
"        QComboBox::down-arrow {\n"
"            border: none;\n"
"            color: white;\n"
"            padding-right: 1px;\n"
"            width: 5px;\n"
"            height: 8px;\n"
"        }\n"
"        QComboBox:on {\n"
"            border: 1px solid #26648E;\n"
"        }\n"
"        QComboBox QListView {\n"
"            border: 1px solid #984063;\n"
"            border-radius: 4px;\n"
"            padding: 5px;\n"
"            background-color: #fff;\n"
"            outline: 0px;\n"
"        }\n"
"        QComboBox QListView::item {\n"
"            padding-left: 5px;\n"
"            background-color: #fff;\n"
"        }\n"
"        QComboBox QListView::item:hover {\n"
"            background-color: #96a4c5;\n"
"        }\n"
"        QComboBox QListView::item:selected {\n"
"            background-color: #96a4c5;\n"
"        }")
        self.widget.setObjectName("widget")
        self.taxRateLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.taxRateLineEdit.setGeometry(QtCore.QRect(230, 295, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.taxRateLineEdit.setFont(font)
        self.taxRateLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.taxRateLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.taxRateLineEdit.setText("")
        self.taxRateLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.taxRateLineEdit.setClearButtonEnabled(True)
        self.taxRateLineEdit.setObjectName("taxRateLineEdit")
        self.stockQuantityLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.stockQuantityLineEdit.setGeometry(QtCore.QRect(40, 225, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.stockQuantityLineEdit.setFont(font)
        self.stockQuantityLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.stockQuantityLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.stockQuantityLineEdit.setText("")
        self.stockQuantityLineEdit.setClearButtonEnabled(True)
        self.stockQuantityLineEdit.setObjectName("stockQuantityLineEdit")
        self.okButton = QtWidgets.QPushButton(parent=self.widget)
        self.okButton.setGeometry(QtCore.QRect(120, 445, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(True)
        self.okButton.setFont(font)
        self.okButton.setStyleSheet("")
        self.okButton.setObjectName("okButton")
        self.addItemLabel = QtWidgets.QLabel(parent=self.widget)
        self.addItemLabel.setGeometry(QtCore.QRect(30, 25, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(18)
        font.setBold(True)
        self.addItemLabel.setFont(font)
        self.addItemLabel.setStyleSheet("color:#26648E;")
        self.addItemLabel.setObjectName("addItemLabel")
        self.itemNameLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.itemNameLineEdit.setGeometry(QtCore.QRect(40, 85, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.itemNameLineEdit.setFont(font)
        self.itemNameLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.itemNameLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferLowercase|QtCore.Qt.InputMethodHint.ImhPreferUppercase)
        self.itemNameLineEdit.setClearButtonEnabled(True)
        self.itemNameLineEdit.setObjectName("itemNameLineEdit")
        self.itemCodeLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.itemCodeLineEdit.setGeometry(QtCore.QRect(390, 85, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.itemCodeLineEdit.setFont(font)
        self.itemCodeLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.itemCodeLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferLowercase|QtCore.Qt.InputMethodHint.ImhPreferNumbers|QtCore.Qt.InputMethodHint.ImhPreferUppercase)
        self.itemCodeLineEdit.setText("")
        self.itemCodeLineEdit.setClearButtonEnabled(True)
        self.itemCodeLineEdit.setObjectName("itemCodeLineEdit")
        self.cancelButton = QtWidgets.QPushButton(parent=self.widget)
        self.cancelButton.setGeometry(QtCore.QRect(290, 445, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(True)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("")
        self.cancelButton.setObjectName("cancelButton")
        self.containerLabel = QtWidgets.QLabel(parent=self.widget)
        self.containerLabel.setGeometry(QtCore.QRect(0, 0, 581, 531))
        self.containerLabel.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"border:3px solid #984063;")
        self.containerLabel.setText("")
        self.containerLabel.setObjectName("containerLabel")
        self.hsnLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.hsnLineEdit.setGeometry(QtCore.QRect(40, 155, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.hsnLineEdit.setFont(font)
        self.hsnLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.hsnLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferLowercase|QtCore.Qt.InputMethodHint.ImhPreferNumbers|QtCore.Qt.InputMethodHint.ImhPreferUppercase)
        self.hsnLineEdit.setText("")
        self.hsnLineEdit.setClearButtonEnabled(True)
        self.hsnLineEdit.setObjectName("hsnLineEdit")
        self.salePriceLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.salePriceLineEdit.setGeometry(QtCore.QRect(230, 155, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.salePriceLineEdit.setFont(font)
        self.salePriceLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.salePriceLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.salePriceLineEdit.setText("")
        self.salePriceLineEdit.setClearButtonEnabled(True)
        self.salePriceLineEdit.setObjectName("salePriceLineEdit")
        self.purchasePriceLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.purchasePriceLineEdit.setGeometry(QtCore.QRect(390, 155, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.purchasePriceLineEdit.setFont(font)
        self.purchasePriceLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.purchasePriceLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.purchasePriceLineEdit.setText("")
        self.purchasePriceLineEdit.setClearButtonEnabled(True)
        self.purchasePriceLineEdit.setObjectName("purchasePriceLineEdit")
        self.mfgDateLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.mfgDateLineEdit.setGeometry(QtCore.QRect(230, 225, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.mfgDateLineEdit.setFont(font)
        self.mfgDateLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.mfgDateLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDate)
        self.mfgDateLineEdit.setText("")
        self.mfgDateLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.mfgDateLineEdit.setReadOnly(True)
        self.mfgDateLineEdit.setClearButtonEnabled(True)
        self.mfgDateLineEdit.setObjectName("mfgDateLineEdit")
        self.expDateLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.expDateLineEdit.setGeometry(QtCore.QRect(390, 225, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.expDateLineEdit.setFont(font)
        self.expDateLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.expDateLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDate)
        self.expDateLineEdit.setText("")
        self.expDateLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.expDateLineEdit.setReadOnly(True)
        self.expDateLineEdit.setClearButtonEnabled(True)
        self.expDateLineEdit.setObjectName("expDateLineEdit")
        self.inclusiveOfTaxComboBox = QtWidgets.QComboBox(parent=self.widget)
        self.inclusiveOfTaxComboBox.setGeometry(QtCore.QRect(40, 300, 171, 33))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(13)
        self.inclusiveOfTaxComboBox.setFont(font)
        self.inclusiveOfTaxComboBox.setEditable(False)
        self.inclusiveOfTaxComboBox.setCurrentText("")
        self.inclusiveOfTaxComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.inclusiveOfTaxComboBox.setFrame(False)
        self.inclusiveOfTaxComboBox.setPlaceholderText("Inclusive Of Tax*")
        self.inclusiveOfTaxComboBox.setObjectName("inclusiveOfTaxComboBox")
        self.inclusiveOfTaxComboBox.addItem("")
        self.inclusiveOfTaxComboBox.addItem("")
        self.addFieldLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.addFieldLineEdit.setGeometry(QtCore.QRect(40, 365, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.addFieldLineEdit.setFont(font)
        self.addFieldLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.addFieldLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.addFieldLineEdit.setText("")
        self.addFieldLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.addFieldLineEdit.setClearButtonEnabled(True)
        self.addFieldLineEdit.setObjectName("addFieldLineEdit")
        self.expDateEdit = QtWidgets.QDateEdit(parent=self.widget)
        self.expDateEdit.setGeometry(QtCore.QRect(430, 225, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        self.expDateEdit.setFont(font)
        self.expDateEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:5px;")
        self.expDateEdit.setCalendarPopup(False)
        self.expDateEdit.setObjectName("expDateEdit")
        self.mfgDateEdit = QtWidgets.QDateEdit(parent=self.widget)
        self.mfgDateEdit.setGeometry(QtCore.QRect(270, 225, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(11)
        self.mfgDateEdit.setFont(font)
        self.mfgDateEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:5px;")
        self.mfgDateEdit.setCalendarPopup(False)
        self.mfgDateEdit.setObjectName("mfgDateEdit")
        self.GSTINLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.GSTINLineEdit.setGeometry(QtCore.QRect(390, 295, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.GSTINLineEdit.setFont(font)
        self.GSTINLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.GSTINLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.GSTINLineEdit.setText("")
        self.GSTINLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Normal)
        self.GSTINLineEdit.setClearButtonEnabled(True)
        self.GSTINLineEdit.setObjectName("GSTINLineEdit")
        self.containerLabel.raise_()
        self.taxRateLineEdit.raise_()
        self.stockQuantityLineEdit.raise_()
        self.okButton.raise_()
        self.addItemLabel.raise_()
        self.itemNameLineEdit.raise_()
        self.itemCodeLineEdit.raise_()
        self.cancelButton.raise_()
        self.hsnLineEdit.raise_()
        self.salePriceLineEdit.raise_()
        self.purchasePriceLineEdit.raise_()
        self.mfgDateLineEdit.raise_()
        self.expDateLineEdit.raise_()
        self.inclusiveOfTaxComboBox.raise_()
        self.addFieldLineEdit.raise_()
        self.expDateEdit.raise_()
        self.mfgDateEdit.raise_()
        self.GSTINLineEdit.raise_()

        
        self.okButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))
        self.cancelButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.taxRateLineEdit.setPlaceholderText(_translate("Form", "Tax Rate %*"))
        self.stockQuantityLineEdit.setPlaceholderText(_translate("Form", "Stock Quantity*"))
        self.okButton.setText(_translate("Form", "Ok"))
        self.addItemLabel.setText(_translate("Form", "Add Item"))
        self.itemNameLineEdit.setPlaceholderText(_translate("Form", "Item Name*"))
        self.itemCodeLineEdit.setPlaceholderText(_translate("Form", "Item Code*"))
        self.cancelButton.setText(_translate("Form", "Cancel"))
        self.hsnLineEdit.setPlaceholderText(_translate("Form", "HSN*"))
        self.salePriceLineEdit.setPlaceholderText(_translate("Form", "Sale Price*"))
        self.purchasePriceLineEdit.setPlaceholderText(_translate("Form", "Purchase Price*"))
        self.mfgDateLineEdit.setPlaceholderText(_translate("Form", "Mfg*"))
        self.expDateLineEdit.setPlaceholderText(_translate("Form", "Exp*"))
        self.inclusiveOfTaxComboBox.setPlaceholderText(_translate("Form", "Inclusive Of Tax*"))
        self.inclusiveOfTaxComboBox.setItemText(0, _translate("Form", "Yes"))
        self.inclusiveOfTaxComboBox.setItemText(1, _translate("Form", "No"))
        self.addFieldLineEdit.setPlaceholderText(_translate("Form", "Additional info"))
        self.expDateEdit.setSpecialValueText(_translate("Form", "Exp. Date*"))
        self.expDateEdit.setDisplayFormat(_translate("Form", "yyyy-MM-dd"))
        self.mfgDateEdit.setSpecialValueText(_translate("Form", "Exp. Date*"))
        self.mfgDateEdit.setDisplayFormat(_translate("Form", "yyyy-MM-dd"))
        self.GSTINLineEdit.setPlaceholderText(_translate("Form", "GSTIN*"))
