# Form implementation generated from reading ui file 'adminMenuUi.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class AdminMenu_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.screen = QtWidgets.QApplication.primaryScreen()
        self.screen_geometry = self.screen.geometry()
        self.screen_width = self.screen_geometry.width()
        self.screen_height = self.screen_geometry.height()
        Form.resize(self.screen_width, self.screen_height)
        Form.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(5, 5, 301, 341))
        self.widget.setStyleSheet("QPushButton#logOutButton{\n"
"    background-color:#41436A;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#logOutButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#F64668;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#logOutButton:hover{\n"
"    background-color:#F64668;\n"
"}\n"
"QToolButton#settingsButton{\n"
"    background-color:#41436A;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:15px;\n"
"padding-bottom:3px;\n"
"}\n"
"QToolButton#settingsButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#F64668;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QToolButton#settingsButton:hover{\n"
"    background-color:#F64668;\n"
"}\n"
"QPushButton#logsButton{\n"
"    background-color:#41436A;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:15px;\n"
"padding-bottom:0px;\n"
"}\n"
"QPushButton#logsButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#F64668;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#logsButton:hover{\n"
"    background-color:#F64668;\n"
"}\n"
"QPushButton{\n"
"    background-color:#984063;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:5px;"
"}\n"
"QPushButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#26648E;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:#26648E;\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.menuLabel = QtWidgets.QLabel(parent=self.widget)
        self.menuLabel.setGeometry(QtCore.QRect(20, 20, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(18)
        font.setBold(True)
        self.menuLabel.setFont(font)
        self.menuLabel.setStyleSheet("color:#41436A;")
        self.menuLabel.setObjectName("menuLabel")
        self.settingsButton = QtWidgets.QToolButton(parent=self.widget)
        self.settingsButton.setGeometry(QtCore.QRect(235,22, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Heading Semibold")
        font.setPointSize(16)
        font.setBold(True)
        self.settingsButton.setFont(font)
        self.settingsButton.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.settingsButton.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.settingsButton.setObjectName("settingsButton")
        self.logsButton = QtWidgets.QPushButton(parent=self.widget)
        self.logsButton.setGeometry(QtCore.QRect(195,22,31,31))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(13)
        font.setBold(True)
        self.logsButton.setFont(font)
        self.logsButton.setStyleSheet("")
        self.logsButton.setObjectName("logsButton")
        self.logOutButton = QtWidgets.QPushButton(parent=self.widget)
        self.logOutButton.setGeometry(QtCore.QRect(20, 270, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(True)
        self.logOutButton.setFont(font)
        self.logOutButton.setStyleSheet("")
        self.logOutButton.setObjectName("logOutButton")
        self.containerLabel = QtWidgets.QLabel(parent=self.widget)
        self.containerLabel.setGeometry(QtCore.QRect(0, 5, 291, 331))
        self.containerLabel.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"border:3px solid #41436A;")
        self.containerLabel.setText("")
        self.containerLabel.setObjectName("containerLabel")
        self.resetPasswordButton = QtWidgets.QPushButton(parent=self.widget)
        self.resetPasswordButton.setGeometry(QtCore.QRect(20, 220, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(True)
        self.resetPasswordButton.setFont(font)
        self.resetPasswordButton.setStyleSheet("")
        self.resetPasswordButton.setObjectName("resetPasswordButton")
        self.newEmployeeButton = QtWidgets.QPushButton(parent=self.widget)
        self.newEmployeeButton.setGeometry(QtCore.QRect(20, 170, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(True)
        self.newEmployeeButton.setFont(font)
        self.newEmployeeButton.setStyleSheet("")
        self.newEmployeeButton.setObjectName("newEmployeeButton")
        self.salesButton = QtWidgets.QPushButton(parent=self.widget)
        self.salesButton.setGeometry(QtCore.QRect(20, 70, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(True)
        self.salesButton.setFont(font)
        self.salesButton.setStyleSheet("")
        self.salesButton.setObjectName("salesButton")
        self.servicesButton = QtWidgets.QPushButton(parent=self.widget)
        self.servicesButton.setGeometry(QtCore.QRect(20, 120, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(True)
        self.servicesButton.setFont(font)
        self.servicesButton.setStyleSheet("")
        self.servicesButton.setObjectName("servicesButton")
        self.containerLabel.raise_()
        self.menuLabel.raise_()
        self.logOutButton.raise_()
        self.resetPasswordButton.raise_()
        self.newEmployeeButton.raise_()
        self.salesButton.raise_()
        self.servicesButton.raise_()
        self.settingsButton.raise_()
        self.logsButton.raise_()

        
        self.servicesButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))
        self.salesButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))
        self.newEmployeeButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))
        self.resetPasswordButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))
        self.logOutButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))
        self.settingsButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))
        self.logsButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.menuLabel.setText(_translate("Form", "Menu"))
        self.logOutButton.setText(_translate("Form", "Log out"))
        self.resetPasswordButton.setText(_translate("Form", "Reset Password"))
        self.newEmployeeButton.setText(_translate("Form", "Register Employee"))
        self.salesButton.setText(_translate("Form", "Sales"))
        self.servicesButton.setText(_translate("Form", "Services"))
        self.settingsButton.setText(_translate("MainWindow", "⚙️"))
        self.logsButton.setText(_translate("MainWindow", "✍️"))
