# Form implementation generated from reading ui file 'enterValueBigUi.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class ValueEntryBig_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.screen = QtWidgets.QApplication.primaryScreen()
        self.screen_geometry = self.screen.geometry()
        self.screen_width = self.screen_geometry.width()
        self.screen_height = self.screen_geometry.height()
        Form.resize(self.screen_width, self.screen_height)
        Form.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 551, 671))
        self.widget.setStyleSheet("QPushButton#okButton{\n"
"    background-color:#984063;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#okButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#26648E;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#okButton:hover{\n"
"    background-color:#26648E;\n"
"}\n"
"QPushButton#cancelButton{\n"
"    background-color:#984063;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#cancelButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#26648E;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#cancelButton:hover{\n"
"    background-color:#26648E;\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.containerLabel = QtWidgets.QLabel(parent=self.widget)
        self.containerLabel.setGeometry(QtCore.QRect(10, 10, 531, 641))
        self.containerLabel.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"border:3px solid #984063;")
        self.containerLabel.setText("")
        self.containerLabel.setObjectName("containerLabel")
        self.sampleIdLabel = QtWidgets.QLabel(parent=self.widget)
        self.sampleIdLabel.setGeometry(QtCore.QRect(50, 30, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(18)
        font.setBold(True)
        self.sampleIdLabel.setFont(font)
        self.sampleIdLabel.setStyleSheet("color:#26648E;")
        self.sampleIdLabel.setObjectName("sampleIdLabel")
        self.okButton = QtWidgets.QPushButton(parent=self.widget)
        self.okButton.setGeometry(QtCore.QRect(110, 580, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(True)
        self.okButton.setFont(font)
        self.okButton.setStyleSheet("")
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(parent=self.widget)
        self.cancelButton.setGeometry(QtCore.QRect(290, 580, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(True)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("")
        self.cancelButton.setObjectName("cancelButton")
        self.sampleIdValueLabel = QtWidgets.QLabel(parent=self.widget)
        self.sampleIdValueLabel.setGeometry(QtCore.QRect(170, 30, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(18)
        font.setBold(False)
        self.sampleIdValueLabel.setFont(font)
        self.sampleIdValueLabel.setStyleSheet("color:#26648E;")
        self.sampleIdValueLabel.setText("")
        self.sampleIdValueLabel.setObjectName("sampleIdValueLabel")
        self.testNameLabel = QtWidgets.QLabel(parent=self.widget)
        self.testNameLabel.setGeometry(QtCore.QRect(85, 70, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(18)
        font.setBold(False)
        self.testNameLabel.setFont(font)
        self.testNameLabel.setStyleSheet("color:#26648E;")
        self.testNameLabel.setText("")
        self.testNameLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.testNameLabel.setObjectName("testNameLabel")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.widget)
        self.plainTextEdit.setGeometry(QtCore.QRect(60, 230, 431, 271))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        font.setBold(False)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setStyleSheet("")
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.resultLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.resultLineEdit.setGeometry(QtCore.QRect(60, 520, 431, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.resultLineEdit.setFont(font)
        self.resultLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.resultLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferLowercase|QtCore.Qt.InputMethodHint.ImhPreferUppercase)
        self.resultLineEdit.setMaxLength(100)
        self.resultLineEdit.setClearButtonEnabled(True)
        self.resultLineEdit.setObjectName("resultLineEdit")
        self.image1Button = QtWidgets.QPushButton(parent=self.widget)
        self.image1Button.setGeometry(QtCore.QRect(60, 150, 103, 29))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        self.image1Button.setFont(font)
        self.image1Button.setObjectName("image1Button")
        self.image1Label = QtWidgets.QLabel(parent=self.widget)
        self.image1Label.setGeometry(QtCore.QRect(170, 120, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        self.image1Label.setFont(font)
        self.image1Label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.image1Label.setStyleSheet("color:#26648E;")
        self.image1Label.setText("")
        self.image1Label.setScaledContents(True)
        self.image1Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.image1Label.setObjectName("image1Label")
        self.image2Button = QtWidgets.QPushButton(parent=self.widget)
        self.image2Button.setGeometry(QtCore.QRect(280, 150, 103, 29))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        self.image2Button.setFont(font)
        self.image2Button.setObjectName("image2Button")
        self.image2Label = QtWidgets.QLabel(parent=self.widget)
        self.image2Label.setGeometry(QtCore.QRect(390, 120, 101, 101))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        self.image2Label.setFont(font)
        self.image2Label.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.image2Label.setStyleSheet("color:#26648E;")
        self.image2Label.setText("")
        self.image2Label.setScaledContents(True)
        self.image2Label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.image2Label.setObjectName("image2Label")

        self.okButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))
        self.cancelButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sampleIdLabel.setText(_translate("Form", "Sample ID :"))
        self.okButton.setText(_translate("Form", "Ok"))
        self.cancelButton.setText(_translate("Form", "Cancel"))
        self.plainTextEdit.setPlaceholderText(_translate("Form", "Sequence data*"))
        self.resultLineEdit.setPlaceholderText(_translate("Form", "Result*"))
        self.image1Button.setText(_translate("Form", "Upload Image 1*"))
        self.image2Button.setText(_translate("Form", "Upload Image 2"))
