# Form implementation generated from reading ui file 'loginUi.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Login_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.screen = QtWidgets.QApplication.primaryScreen()
        self.screen_geometry = self.screen.geometry()
        self.screen_width = self.screen_geometry.width()
        self.screen_height = self.screen_geometry.height()
        Form.resize(self.screen_width, self.screen_height)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(5, 5, 651, 461))
        font = QtGui.QFont()
        self.widget.setFont(font)
        self.widget.setStyleSheet("QPushButton#logInButton{\n"
"    background-color:#41436A;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#logInButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#F64668;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#logInButton:hover{\n"
"    background-color:#F64668;\n"
"}\n"
"QPushButton#signUpButton{\n"
"    background-color:#41436A;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#signUpButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#F64668;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#signUpButton:hover{\n"
"    background-color:#F64668;\n"
"}")
        self.widget.setObjectName("widget")
        self.loginContainerLabel = QtWidgets.QLabel(parent=self.widget)
        self.loginContainerLabel.setGeometry(QtCore.QRect(350, 60, 300, 341))
        self.loginContainerLabel.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:3px solid #41436A;\n"
"border-radius:20px;")
        self.loginContainerLabel.setText("")
        self.loginContainerLabel.setObjectName("loginContainerLabel")
        self.logInButton = QtWidgets.QPushButton(parent=self.widget)
        self.logInButton.setGeometry(QtCore.QRect(390, 326, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(True)
        self.logInButton.setFont(font)
        self.logInButton.setStyleSheet("")
        self.logInButton.setObjectName("logInButton")
        self.parGroupContainerLabel = QtWidgets.QLabel(parent=self.widget)
        self.parGroupContainerLabel.setGeometry(QtCore.QRect(0, 6, 370, 450))
        self.parGroupContainerLabel.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 #F64668 , stop:1 #41436A);\n"
"border-radius:20px;\n"
"border:3px solid #41436A;")
        self.parGroupContainerLabel.setText("")
        self.parGroupContainerLabel.setObjectName("parGroupContainerLabel")
        self.usernameLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.usernameLineEdit.setGeometry(QtCore.QRect(390, 156, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.usernameLineEdit.setFont(font)
        self.usernameLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#41436A;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.usernameLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText|QtCore.Qt.InputMethodHint.ImhPreferLowercase|QtCore.Qt.InputMethodHint.ImhPreferNumbers|QtCore.Qt.InputMethodHint.ImhPreferUppercase|QtCore.Qt.InputMethodHint.ImhSensitiveData)
        self.usernameLineEdit.setMaxLength(20)
        self.usernameLineEdit.setClearButtonEnabled(True)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.descriptionLabel = QtWidgets.QLabel(parent=self.widget)
        self.descriptionLabel.setGeometry(QtCore.QRect(20, 96, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(15)
        font.setBold(True)
        self.descriptionLabel.setFont(font)
        self.descriptionLabel.setStyleSheet("color:#FFFFFF;")
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.parGroupLabel = QtWidgets.QLabel(parent=self.widget)
        self.parGroupLabel.setGeometry(QtCore.QRect(20, 36, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(36)
        font.setBold(True)
        self.parGroupLabel.setFont(font)
        self.parGroupLabel.setStyleSheet("color:#FFFFFF;")
        self.parGroupLabel.setObjectName("parGroupLabel")
        self.logInLabel = QtWidgets.QLabel(parent=self.widget)
        self.logInLabel.setGeometry(QtCore.QRect(390, 81, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(24)
        font.setBold(True)
        self.logInLabel.setFont(font)
        self.logInLabel.setStyleSheet("color:#41436A;")
        self.logInLabel.setObjectName("logInLabel")
        self.passwordLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.passwordLineEdit.setGeometry(QtCore.QRect(390, 226, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#41436A;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.passwordLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText|QtCore.Qt.InputMethodHint.ImhNoAutoUppercase|QtCore.Qt.InputMethodHint.ImhNoPredictiveText|QtCore.Qt.InputMethodHint.ImhPreferLowercase|QtCore.Qt.InputMethodHint.ImhPreferNumbers|QtCore.Qt.InputMethodHint.ImhPreferUppercase|QtCore.Qt.InputMethodHint.ImhSensitiveData)
        self.passwordLineEdit.setMaxLength(15)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordLineEdit.setClearButtonEnabled(True)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(-40, 100, 371, 341))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.logInButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.logInButton.setText(_translate("Form", "Log In"))
        self.usernameLineEdit.setPlaceholderText(_translate("Form", "Username"))
        self.descriptionLabel.setText(_translate("Form", "Life Science & Research Pvt. Ltd."))
        self.parGroupLabel.setText(_translate("Form", "PAR Group"))
        self.logInLabel.setText(_translate("Form", "Log In"))
        self.passwordLineEdit.setPlaceholderText(_translate("Form", "Password"))
