# Form implementation generated from reading ui file 'mainAccSaleAnalysisUi.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
from win32gui import GetWindowRect, GetForegroundWindow
screen_width = GetWindowRect(GetForegroundWindow())[2]
screen_height = GetWindowRect(GetForegroundWindow())[3]


class AccSaleAnalysis_Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.screen_width = screen_width
        self.screen_height = screen_height
        MainWindow.resize(self.screen_width, self.screen_height)
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        MainWindow.setStyleSheet("QPushButton#logOutButton{\n"
"    background-color:#41436A;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#logOutButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#F64668;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#logOutButton:hover{\n"
"    background-color:#F64668;\n"
"}\n"
"QPushButton#salesButton{\n"
"    background-color:#984063;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#salesButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#26648E;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#salesButton:hover{\n"
"    background-color:#26648E;\n"
"}\n"
"QPushButton#servicesButton{\n"
"    background-color:#984063;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#servicesButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#26648E;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#servicesButton:hover{\n"
"    background-color:#26648E;\n"
"}\n"
"QToolButton#reloadButton {\n"
"    background-color: #984063;\n"
"    color: rgba(255, 255, 255, 200);\n"
"    border-radius: 15px;\n"
"    padding-bottom: 6px;\n"
"}\n"
"QToolButton#reloadButton:pressed {\n"
"    padding-left: 5px;\n"
"    padding-top: 5px;\n"
"    background-color: #26648E;\n"
"    background-position: calc(100% - 10px) center;\n"
"}\n"
"QToolButton#reloadButton:hover {\n"
"    background-color: #26648E;\n"
"}\n"
"\n"
"\n"
"background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.parGroupLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.parGroupLabel.setGeometry(QtCore.QRect(120, 20, 291, 51))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(28)
        font.setBold(True)
        self.parGroupLabel.setFont(font)
        self.parGroupLabel.setStyleSheet("color:rgba(255, 255, 255, 220);")
        self.parGroupLabel.setObjectName("parGroupLabel")
        self.descriptionLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.descriptionLabel.setGeometry(QtCore.QRect(120, 70, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(15)
        font.setBold(True)
        self.descriptionLabel.setFont(font)
        self.descriptionLabel.setStyleSheet("color:rgba(255, 255, 255, 220);\n"
"")
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.topLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.topLabel.setGeometry(QtCore.QRect(5, 10, int(self.screen_width*0.996)-2, 111))
        self.topLabel.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #41436A , stop:1 #F64668);\n"
"border-radius: 20px;\n"
"")
        self.topLabel.setText("")
        self.topLabel.setObjectName("topLabel")
        self.logOutButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.logOutButton.setGeometry(QtCore.QRect(int(self.screen_width*0.915)-2, 45, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(True)
        self.logOutButton.setFont(font)
        self.logOutButton.setStyleSheet("")
        self.logOutButton.setObjectName("logOutButton")
        logOutButton_geometry = self.logOutButton.geometry()
        logOutButton_left = logOutButton_geometry.left()
        Label_x = logOutButton_left - 151 - 10
        self.containerLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.containerLabel.setEnabled(True)
        self.containerLabel.setGeometry(QtCore.QRect(0, -1, int(self.screen_width), int(self.screen_height*0.974)))
        self.containerLabel.setStyleSheet("background-color:rgb(255, 255, 255);\n""border: none;"
"")
        self.containerLabel.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.containerLabel.setText("")
        self.containerLabel.setObjectName("containerLabel")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(9, 170, 1591, 665))
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 90, int(self.screen_width*0.98), int(self.screen_height*0.69)))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 70, int(self.screen_width*0.95), 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.yearComboBox = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget)
        self.yearComboBox.setMaximumSize(QtCore.QSize(290, 16777215))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(12)
        font.setBold(False)
        self.yearComboBox.setFont(font)
        self.yearComboBox.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.yearComboBox.setAcceptDrops(False)
        self.yearComboBox.setEditable(False)
        self.yearComboBox.setCurrentText("")
        self.yearComboBox.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAtBottom)
        self.yearComboBox.setFrame(True)
        self.yearComboBox.setPlaceholderText("Yearly-wise")
        self.yearComboBox.setObjectName("yearComboBox")
        self.horizontalLayout.addWidget(self.yearComboBox)
        self.monthComboBox = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget)
        self.monthComboBox.setMaximumSize(QtCore.QSize(290, 16777215))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(12)
        font.setBold(False)
        self.monthComboBox.setFont(font)
        self.monthComboBox.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.monthComboBox.setAcceptDrops(False)
        self.monthComboBox.setEditable(False)
        self.monthComboBox.setCurrentText("")
        self.monthComboBox.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAtBottom)
        self.monthComboBox.setFrame(True)
        self.monthComboBox.setPlaceholderText("Monthly-wise")
        self.monthComboBox.setObjectName("monthComboBox")
        self.horizontalLayout.addWidget(self.monthComboBox)
        self.dailyComboBox = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget)
        self.dailyComboBox.setMaximumSize(QtCore.QSize(290, 16777215))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(12)
        font.setBold(False)
        self.dailyComboBox.setFont(font)
        self.dailyComboBox.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.dailyComboBox.setAcceptDrops(False)
        self.dailyComboBox.setEditable(False)
        self.dailyComboBox.setCurrentText("")
        self.dailyComboBox.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAtBottom)
        self.dailyComboBox.setPlaceholderText("Daily-wise")
        self.dailyComboBox.setObjectName("dailyComboBox")
        self.dailyComboBox.addItem("")
        self.dailyComboBox.addItem("")
        self.dailyComboBox.addItem("")
        self.dailyComboBox.addItem("")
        self.dailyComboBox.addItem("")
        self.dailyComboBox.addItem("")
        self.dailyComboBox.addItem("")
        self.dailyComboBox.addItem("")
        self.dailyComboBox.addItem("")
        self.dailyComboBox.addItem("")
        self.dailyComboBox.addItem("")
        self.dailyComboBox.addItem("")
        self.horizontalLayout.addWidget(self.dailyComboBox)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(parent=self.widget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 20, int(self.screen_width*0.95), 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.categoryComboBox = QtWidgets.QComboBox(parent=self.horizontalLayoutWidget_2)
        self.categoryComboBox.setMaximumSize(QtCore.QSize(290, 16777215))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(12)
        font.setBold(False)
        self.categoryComboBox.setFont(font)
        self.categoryComboBox.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.categoryComboBox.setAcceptDrops(False)
        self.categoryComboBox.setEditable(False)
        self.categoryComboBox.setCurrentText("")
        self.categoryComboBox.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAtBottom)
        self.categoryComboBox.setFrame(True)
        self.categoryComboBox.setPlaceholderText("Category")
        self.categoryComboBox.setObjectName("categoryComboBox")
        self.categoryComboBox.addItem("")
        self.categoryComboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.categoryComboBox)
        self.saleAnalysisLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.saleAnalysisLabel.setGeometry(QtCore.QRect(25, 130, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(18)
        font.setBold(True)
        self.saleAnalysisLabel.setFont(font)
        self.saleAnalysisLabel.setStyleSheet("color:#41436A;")
        self.saleAnalysisLabel.setObjectName("saleAnalysisLabel")
        self.reloadButton = QtWidgets.QToolButton(parent=self.centralwidget)
        self.reloadButton.setGeometry(QtCore.QRect(self.containerLabel.geometry().right()-31-25, 130, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Heading Semibold")
        font.setPointSize(20)
        font.setBold(True)
        self.reloadButton.setFont(font)
        self.reloadButton.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.DelayedPopup)
        self.reloadButton.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        self.reloadButton.setObjectName("reloadButton")
        self.fig = Figure()
        self.canvas=FigureCanvas(self.fig)
        self.verticalLayout.addWidget(self.canvas)
        self.axes = self.fig.add_subplot()
        self.axes.spines['top'].set_visible(False)
        self.axes.spines['right'].set_visible(False)
        self.axes.spines['bottom'].set_visible(False)
        self.axes.spines['left'].set_visible(False)
        self.axes.set_facecolor('#E5ECF6')
        self.fig.subplots_adjust(bottom=0.239)
        self.roleLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.roleLabel.setGeometry(QtCore.QRect(Label_x, 70, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(True)
        self.roleLabel.setFont(font)
        self.roleLabel.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.roleLabel.setStyleSheet("color:rgba(255, 255, 255, 220);\n"
"")
        self.roleLabel.setText("")
        self.roleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.roleLabel.setObjectName("roleLabel")
        self.nameLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(logOutButton_left - 151 - 100, 52, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(True)
        self.nameLabel.setFont(font)
        self.nameLabel.setLayoutDirection(QtCore.Qt.LayoutDirection.RightToLeft)
        self.nameLabel.setStyleSheet("color:rgba(255, 255, 255, 220);\n"
"")
        self.nameLabel.setText("")
        self.nameLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.salesButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.salesButton.setGeometry(QtCore.QRect(190, 125, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(True)
        self.salesButton.setFont(font)
        self.salesButton.setStyleSheet("")
        self.salesButton.setObjectName("salesButton")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 81, 71))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("PAR Logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        
        self.containerLabel.raise_()
        self.topLabel.raise_()
        self.descriptionLabel.raise_()
        self.logOutButton.raise_()
        self.parGroupLabel.raise_()
        self.widget.raise_()
        self.saleAnalysisLabel.raise_()
        self.reloadButton.raise_()
        self.roleLabel.raise_()
        self.nameLabel.raise_()
        self.salesButton.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.parGroupLabel.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=0,yOffset=0))
        self.descriptionLabel.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=0,yOffset=0))
        self.topLabel.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=0,yOffset=0))
        self.containerLabel.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=0,yOffset=0))
        self.logOutButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))
        self.salesButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))
        self.reloadButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.parGroupLabel.setText(_translate("MainWindow", "PAR Group"))
        self.descriptionLabel.setText(_translate("MainWindow", "Life Science & Research Pvt. Ltd."))
        self.logOutButton.setText(_translate("MainWindow", "Log Out"))
        self.yearComboBox.setPlaceholderText(_translate("MainWindow", "Yearly-wise (Choose)"))
        self.monthComboBox.setPlaceholderText(_translate("MainWindow", "Monthly-wise (Choose)"))
        self.dailyComboBox.setPlaceholderText(_translate("MainWindow", "Daily-wise (Choose)"))
        self.dailyComboBox.setItemText(0, _translate("MainWindow", "January"))
        self.dailyComboBox.setItemText(1, _translate("MainWindow", "February"))
        self.dailyComboBox.setItemText(2, _translate("MainWindow", "March"))
        self.dailyComboBox.setItemText(3, _translate("MainWindow", "April"))
        self.dailyComboBox.setItemText(4, _translate("MainWindow", "May"))
        self.dailyComboBox.setItemText(5, _translate("MainWindow", "June"))
        self.dailyComboBox.setItemText(6, _translate("MainWindow", "July"))
        self.dailyComboBox.setItemText(7, _translate("MainWindow", "August"))
        self.dailyComboBox.setItemText(8, _translate("MainWindow", "September"))
        self.dailyComboBox.setItemText(9, _translate("MainWindow", "October"))
        self.dailyComboBox.setItemText(10, _translate("MainWindow", "November"))
        self.dailyComboBox.setItemText(11, _translate("MainWindow", "December"))
        self.categoryComboBox.setPlaceholderText(_translate("MainWindow", "Category"))
        self.categoryComboBox.setItemText(0, _translate("MainWindow", "Sales"))
        self.categoryComboBox.setItemText(1, _translate("MainWindow", "Purchases"))
        self.saleAnalysisLabel.setText(_translate("MainWindow", "Sales Analysis"))
        self.reloadButton.setText(_translate("MainWindow", "⟳"))
        self.salesButton.setText(_translate("MainWindow", "Sales"))
