# Form implementation generated from reading ui file 'newSampleUi.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class NewSample_Ui_Form(object):
    i=1
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.screen = QtWidgets.QApplication.primaryScreen()
        self.screen_geometry = self.screen.geometry()
        self.screen_width = self.screen_geometry.width()
        self.screen_height = self.screen_geometry.height()
        Form.resize(self.screen_width, self.screen_height)
        Form.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 971, 721))
        self.widget.setStyleSheet("QPushButton#okButton{\n"
"    background-color:#984063;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#okButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#26648E;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#okButton:hover{\n"
"    background-color:#26648E;\n"
"}\n"
"QPushButton#cancelButton{\n"
"    background-color:#984063;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:4px;\n"
"}\n"
"QPushButton#cancelButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#26648E;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#cancelButton:hover{\n"
"    background-color:#26648E;\n"
"}\n"
"QPushButton#addButton{\n"
"    background-color:#26648E;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#addButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#984063;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#addButton:hover{\n"
"    background-color:#984063;\n"
"}\n"
"QComboBox {\n"
"            border: 1px solid #984063;\n"
"            border-radius: 5px;\n"
"            padding-left: 4px;\n"
"            padding-right: 15px; \n"
"        }\n"
"        QComboBox::drop-down {\n"
"            subcontrol-origin: padding;\n"
"            subcontrol-position: top right;\n"
"            width: 25px;\n"
"            border-left: 1px solid #984063;\n"
"            border-top-right-radius: 5px;\n"
"            border-bottom-right-radius: 5px;\n"
"            background: #984063;\n"
"        }\n"
"        QComboBox::down-arrow {\n"
"            border: none;\n"
"            color: white;\n"
"            padding-right: 5px;\n"
"            width: 10px;\n"
"            height: 8px;\n"
"        }\n"
"        QComboBox:on {\n"
"            border: 1px solid #26648E;\n"
"        }\n"
"        QComboBox QListView {\n"
"            border: 1px solid #984063;\n"
"            border-radius: 4px;\n"
"            padding: 5px;\n"
"            background-color: #fff;\n"
"            outline: 0px;\n"
"        }\n"
"        QComboBox QListView::item {\n"
"            padding-left: 5px;\n"
"            background-color: #fff;\n"
"        }\n"
"        QComboBox QListView::item:hover {\n"
"            background-color: #96a4c5;\n"
"        }\n"
"        QComboBox QListView::item:selected {\n"
"            background-color: #96a4c5;\n"
"        }\n"
"QScrollArea {\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #f5f5f5;\n"
"    height: 15px;\n"
"    margin: 0px 20px 0 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #b0bec5;\n"
"    min-width: 20px;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: #f5f5f5;\n"
"    width: 20px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: #f5f5f5;\n"
"    width: 20px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #f5f5f5;\n"
"    width: 15px;\n"
"    margin: 20px 0 20px 0;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #b0bec5;\n"
"    min-height: 20px;\n"
"    border-radius: 7px;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    border: none;\n"
"    background: #f5f5f5;\n"
"    height: 20px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: #f5f5f5;\n"
"    height: 20px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}")
        self.widget.setObjectName("widget")
        self.containerLabel = QtWidgets.QLabel(parent=self.widget)
        self.containerLabel.setGeometry(QtCore.QRect(5, 2, 961, 711))
        self.containerLabel.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"border:3px solid #984063;\n"
"")
        self.containerLabel.setText("")
        self.containerLabel.setObjectName("containerLabel")
        self.newLabel = QtWidgets.QLabel(parent=self.widget)
        self.newLabel.setGeometry(QtCore.QRect(445, 12, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(18)
        font.setBold(True)
        self.newLabel.setFont(font)
        self.newLabel.setStyleSheet("color:#984063;")
        self.newLabel.setObjectName("newLabel")
        self.okButton = QtWidgets.QPushButton(parent=self.widget)
        self.okButton.setGeometry(QtCore.QRect(305, 637, 151, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(25)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        self.okButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.okButton.setSizeIncrement(QtCore.QSize(3, 0))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(True)
        self.okButton.setFont(font)
        self.okButton.setStyleSheet("")
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(parent=self.widget)
        self.cancelButton.setGeometry(QtCore.QRect(485, 637, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(True)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("")
        self.cancelButton.setObjectName("cancelButton")
        self.customerDtLabel = QtWidgets.QLabel(parent=self.widget)
        self.customerDtLabel.setGeometry(QtCore.QRect(25, 62, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(18)
        font.setBold(True)
        self.customerDtLabel.setFont(font)
        self.customerDtLabel.setStyleSheet("color:#26648E;")
        self.customerDtLabel.setObjectName("customerDtLabel")
        self.addButton = QtWidgets.QPushButton(parent=self.widget)
        self.addButton.setGeometry(QtCore.QRect(190, 274, 75, 24))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(12)
        font.setBold(False)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.emailLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.emailLineEdit.setGeometry(QtCore.QRect(660, 110, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.emailLineEdit.setFont(font)
        self.emailLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.emailLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhEmailCharactersOnly)
        self.emailLineEdit.setText("")
        self.emailLineEdit.setMaxLength(50)
        self.emailLineEdit.setClearButtonEnabled(True)
        self.emailLineEdit.setObjectName("emailLineEdit")
        self.nameLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.nameLineEdit.setGeometry(QtCore.QRect(55, 110, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.nameLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferLowercase|QtCore.Qt.InputMethodHint.ImhPreferUppercase)
        self.nameLineEdit.setMaxLength(25)
        self.nameLineEdit.setClearButtonEnabled(True)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.addressLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.addressLineEdit.setGeometry(QtCore.QRect(285, 182, 615, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.addressLineEdit.setFont(font)
        self.addressLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.addressLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferLowercase|QtCore.Qt.InputMethodHint.ImhPreferUppercase)
        self.addressLineEdit.setText("")
        self.addressLineEdit.setMaxLength(150)
        self.addressLineEdit.setFrame(True)
        self.addressLineEdit.setClearButtonEnabled(True)
        self.addressLineEdit.setObjectName("addressLineEdit")
        self.MnoLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.MnoLineEdit.setGeometry(QtCore.QRect(55, 182, 200, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.MnoLineEdit.setFont(font)
        self.MnoLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.MnoLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.MnoLineEdit.setText("")
        self.MnoLineEdit.setMaxLength(10)
        self.MnoLineEdit.setClearButtonEnabled(True)
        self.MnoLineEdit.setObjectName("MnoLineEdit")
        self.sampleDtLabel = QtWidgets.QLabel(parent=self.widget)
        self.sampleDtLabel.setGeometry(QtCore.QRect(25, 265, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(18)
        font.setBold(True)
        self.sampleDtLabel.setFont(font)
        self.sampleDtLabel.setStyleSheet("color:#26648E;")
        self.sampleDtLabel.setObjectName("sampleDtLabel")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.widget)
        self.scrollArea.setGeometry(QtCore.QRect(45, 322, 871, 281))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(12)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 871, 281))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.searchLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.searchLineEdit.setGeometry(QtCore.QRect(640, 262, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(12)
        font.setBold(False)
        self.searchLineEdit.setFont(font)
        self.searchLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-color:#26648E;\n"
"border-radius:20px;\n"
"color:rgb(0, 0, 0);\n"
"padding-left:10px;")
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.ageSpinBox = QtWidgets.QSpinBox(parent=self.widget)
        self.ageSpinBox.setGeometry(QtCore.QRect(405, 110, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        self.ageSpinBox.setFont(font)
        self.ageSpinBox.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);")
        self.ageSpinBox.setFrame(True)
        self.ageSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.ageSpinBox.setAccelerated(False)
        self.ageSpinBox.setObjectName("ageSpinBox")
        self.genderComboBox = QtWidgets.QComboBox(parent=self.widget)
        self.genderComboBox.setGeometry(QtCore.QRect(525, 112, 110, 37))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        self.genderComboBox.setFont(font)
        self.genderComboBox.setCurrentText("")
        self.genderComboBox.setPlaceholderText("genderComboBox")
        self.genderComboBox.setObjectName("genderComboBox")
        self.genderComboBox.addItem("")
        self.genderComboBox.addItem("")
        self.genderComboBox.addItem("")

        
        self.okButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))
        self.cancelButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.newLabel.setText(_translate("Form", "New"))
        self.okButton.setText(_translate("Form", "Ok"))
        self.cancelButton.setText(_translate("Form", "Cancel"))
        self.customerDtLabel.setText(_translate("Form", "Customer Details"))
        self.addButton.setText(_translate("Form", "Add"))
        self.emailLineEdit.setPlaceholderText(_translate("Form", "Email ID"))
        self.nameLineEdit.setPlaceholderText(_translate("Form", "Name*"))
        self.addressLineEdit.setPlaceholderText(_translate("Form", "Address*"))
        self.MnoLineEdit.setPlaceholderText(_translate("Form", "Mobile No*"))
        self.sampleDtLabel.setText(_translate("Form", "Sample Details"))
        self.searchLineEdit.setPlaceholderText(_translate("Form", "Search test"))
        self.ageSpinBox.setSpecialValueText(_translate("Form", "Age"))
        self.genderComboBox.setPlaceholderText(_translate("Form", "Gender"))
        self.genderComboBox.setItemText(0, _translate("Form", "Female"))
        self.genderComboBox.setItemText(1, _translate("Form", "Male"))
        self.genderComboBox.setItemText(2, _translate("Form", "Other"))
