# Form implementation generated from reading ui file 'newTestUi.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class NewTest_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.screen = QtWidgets.QApplication.primaryScreen()
        self.screen_geometry = self.screen.geometry()
        self.screen_width = self.screen_geometry.width()
        self.screen_height = self.screen_geometry.height()
        Form.resize(self.screen_width, self.screen_height)
        Form.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(0, 0, 501, 281))
        self.widget.setStyleSheet("QPushButton#okButton{\n"
"    background-color:#984063;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#okButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#26648E;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#okButton:hover{\n"
"    background-color:#26648E;\n"
"}\n"
"QPushButton#cancelButton{\n"
"    background-color:#984063;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:4px;\n"
"}\n"
"QPushButton#cancelButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#26648E;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#cancelButton:hover{\n"
"    background-color:#26648E;\n"
"}\n"
"QPushButton#addButton{\n"
"    background-color:#26648E;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#addButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#984063;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#addButton:hover{\n"
"    background-color:#984063;\n"
"}\n"
"QComboBox {\n"
"            border: 1px solid #984063;\n"
"            border-radius: 5px;\n"
"            padding-left: 4px;\n"
"            padding-right: 8px; \n"
"        }\n"
"        QComboBox::drop-down {\n"
"            subcontrol-origin: padding;\n"
"            subcontrol-position: top right;\n"
"            width: 25px;\n"
"            border-left: 1px solid #984063;\n"
"            border-top-right-radius: 5px;\n"
"            border-bottom-right-radius: 5px;\n"
"            background: #984063;\n"
"        }\n"
"        QComboBox::down-arrow {\n"
"            border: none;\n"
"            color: white;\n"
"            padding-right: 5px;\n"
"            width: 10px;\n"
"            height: 8px;\n"
"        }\n"
"        QComboBox:on {\n"
"            border: 1px solid #26648E;\n"
"        }\n"
"        QComboBox QListView {\n"
"            border: 1px solid #984063;\n"
"            border-radius: 4px;\n"
"            padding: 5px;\n"
"            background-color: #fff;\n"
"            outline: 0px;\n"
"        }\n"
"        QComboBox QListView::item {\n"
"            padding-left: 5px;\n"
"            background-color: #fff;\n"
"        }\n"
"        QComboBox QListView::item:hover {\n"
"            background-color: #96a4c5;\n"
"        }\n"
"        QComboBox QListView::item:selected {\n"
"            background-color: #96a4c5;\n"
"        }")
        self.widget.setObjectName("widget")
        self.containerLabel = QtWidgets.QLabel(parent=self.widget)
        self.containerLabel.setGeometry(QtCore.QRect(0, 0, 501, 281))
        self.containerLabel.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"border:3px solid #984063;\n"
"")
        self.containerLabel.setText("")
        self.containerLabel.setObjectName("containerLabel")
        self.newLabel = QtWidgets.QLabel(parent=self.widget)
        self.newLabel.setGeometry(QtCore.QRect(220, 10, 61, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(18)
        font.setBold(True)
        self.newLabel.setFont(font)
        self.newLabel.setStyleSheet("color:#26648E;")
        self.newLabel.setObjectName("newLabel")
        self.okButton = QtWidgets.QPushButton(parent=self.widget)
        self.okButton.setGeometry(QtCore.QRect(80, 200, 151, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(25)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.okButton.sizePolicy().hasHeightForWidth())
        self.okButton.setSizePolicy(sizePolicy)
        self.okButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.okButton.setSizeIncrement(QtCore.QSize(3, 0))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(True)
        self.okButton.setFont(font)
        self.okButton.setStyleSheet("")
        self.okButton.setObjectName("okButton")
        self.cancelButton = QtWidgets.QPushButton(parent=self.widget)
        self.cancelButton.setGeometry(QtCore.QRect(260, 200, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(True)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("")
        self.cancelButton.setObjectName("cancelButton")
        self.newTestNameLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.newTestNameLineEdit.setGeometry(QtCore.QRect(20, 60, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.newTestNameLineEdit.setFont(font)
        self.newTestNameLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.newTestNameLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferLowercase|QtCore.Qt.InputMethodHint.ImhPreferUppercase)
        self.newTestNameLineEdit.setMaxLength(100)
        self.newTestNameLineEdit.setClearButtonEnabled(True)
        self.newTestNameLineEdit.setObjectName("newTestNameLineEdit")
        self.newTestFeeLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.newTestFeeLineEdit.setGeometry(QtCore.QRect(20, 120, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.newTestFeeLineEdit.setFont(font)
        self.newTestFeeLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.newTestFeeLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly|QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.newTestFeeLineEdit.setMaxLength(100)
        self.newTestFeeLineEdit.setClearButtonEnabled(True)
        self.newTestFeeLineEdit.setObjectName("newTestFeeLineEdit")
        self.newTestGSTINeLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.newTestGSTINeLineEdit.setGeometry(QtCore.QRect(260, 60, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.newTestGSTINeLineEdit.setFont(font)
        self.newTestGSTINeLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.newTestGSTINeLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly|QtCore.Qt.InputMethodHint.ImhPreferLowercase|QtCore.Qt.InputMethodHint.ImhPreferNumbers)
        self.newTestGSTINeLineEdit.setMaxLength(100)
        self.newTestGSTINeLineEdit.setClearButtonEnabled(True)
        self.newTestGSTINeLineEdit.setObjectName("newTestGSTINeLineEdit")
        self.newTestTaxRateLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.newTestTaxRateLineEdit.setGeometry(QtCore.QRect(340, 120, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.newTestTaxRateLineEdit.setFont(font)
        self.newTestTaxRateLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.newTestTaxRateLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferLowercase|QtCore.Qt.InputMethodHint.ImhPreferNumbers|QtCore.Qt.InputMethodHint.ImhPreferUppercase)
        self.newTestTaxRateLineEdit.setMaxLength(100)
        self.newTestTaxRateLineEdit.setClearButtonEnabled(True)
        self.newTestTaxRateLineEdit.setObjectName("newTestTaxRateLineEdit")
        self.inclusiveOfTaxComboBox = QtWidgets.QComboBox(parent=self.widget)
        self.inclusiveOfTaxComboBox.setGeometry(QtCore.QRect(160, 124, 162, 33))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(13)
        self.inclusiveOfTaxComboBox.setFont(font)
        self.inclusiveOfTaxComboBox.setEditable(False)
        self.inclusiveOfTaxComboBox.setCurrentText("")
        self.inclusiveOfTaxComboBox.setFrame(False)
        self.inclusiveOfTaxComboBox.setPlaceholderText("Inclusive Of Tax")
        self.inclusiveOfTaxComboBox.setObjectName("inclusiveOfTaxComboBox")
        self.inclusiveOfTaxComboBox.addItem("")
        self.inclusiveOfTaxComboBox.addItem("")
        self.inclusiveOfTaxComboBox.addItem("")

        
        self.okButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))
        self.cancelButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.newLabel.setText(_translate("Form", "New"))
        self.okButton.setText(_translate("Form", "Ok"))
        self.cancelButton.setText(_translate("Form", "Cancel"))
        self.newTestNameLineEdit.setPlaceholderText(_translate("Form", "Test Name*"))
        self.newTestFeeLineEdit.setPlaceholderText(_translate("Form", "Fee*"))
        self.newTestGSTINeLineEdit.setPlaceholderText(_translate("Form", "GST IN*"))
        self.newTestTaxRateLineEdit.setPlaceholderText(_translate("Form", "Tax Rate %"))
        self.inclusiveOfTaxComboBox.setPlaceholderText(_translate("Form", "Inclusive Of Tax"))
        self.inclusiveOfTaxComboBox.setItemText(0, _translate("Form", "Select"))
        self.inclusiveOfTaxComboBox.setItemText(1, _translate("Form", "Yes"))
        self.inclusiveOfTaxComboBox.setItemText(2, _translate("Form", "No"))
