# Form implementation generated from reading ui file 'removeItemUi.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class RemoveItem_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.screen = QtWidgets.QApplication.primaryScreen()
        self.screen_geometry = self.screen.geometry()
        self.screen_width = self.screen_geometry.width()
        self.screen_height = self.screen_geometry.height()
        Form.resize(self.screen_width, self.screen_height)
        Form.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(5, 5, 471, 311))
        self.widget.setStyleSheet("QPushButton#removeButton{\n"
"    background-color:#984063;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#removeButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#26648E;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#removeButton:hover{\n"
"    background-color:#26648E;\n"
"}\n"
"QPushButton#cancelButton{\n"
"    background-color:#984063;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#cancelButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#26648E;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#cancelButton:hover{\n"
"    background-color:#26648E;\n"
"}\n"
"QComboBox {\n"
"            border: 1px solid #984063;\n"
"            border-radius: 5px;\n"
"            padding-left: 4px;\n"
"            padding-right: 20px; \n"
"        }\n"
"        QComboBox::drop-down {\n"
"            subcontrol-origin: padding;\n"
"            subcontrol-position: top right;\n"
"            width: 25px;\n"
"            border-left: 1px solid #984063;\n"
"            border-top-right-radius: 5px;\n"
"            border-bottom-right-radius: 5px;\n"
"            background: #984063;\n"
"        }\n"
"        QComboBox::down-arrow {\n"
"            border: none;\n"
"            color: white;\n"
"            padding-right: 1px;\n"
"            width: 5px;\n"
"            height: 8px;\n"
"        }\n"
"        QComboBox:on {\n"
"            border: 1px solid #26648E;\n"
"        }\n"
"        QComboBox QListView {\n"
"            border: 1px solid #984063;\n"
"            border-radius: 4px;\n"
"            padding: 5px;\n"
"            background-color: #fff;\n"
"            outline: 0px;\n"
"        }\n"
"        QComboBox QListView::item {\n"
"            padding-left: 5px;\n"
"            background-color: #fff;\n"
"        }\n"
"        QComboBox QListView::item:hover {\n"
"            background-color: #96a4c5;\n"
"        }\n"
"        QComboBox QListView::item:selected {\n"
"            background-color: #96a4c5;\n"
"        }")
        self.widget.setObjectName("widget")
        self.removeButton = QtWidgets.QPushButton(parent=self.widget)
        self.removeButton.setGeometry(QtCore.QRect(75, 230, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(True)
        self.removeButton.setFont(font)
        self.removeButton.setStyleSheet("")
        self.removeButton.setObjectName("removeButton")
        self.removeItemLabel = QtWidgets.QLabel(parent=self.widget)
        self.removeItemLabel.setGeometry(QtCore.QRect(20, 20, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(18)
        font.setBold(True)
        self.removeItemLabel.setFont(font)
        self.removeItemLabel.setStyleSheet("color:#26648E;")
        self.removeItemLabel.setObjectName("removeItemLabel")
        self.itemNameLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.itemNameLineEdit.setGeometry(QtCore.QRect(40, 80, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.itemNameLineEdit.setFont(font)
        self.itemNameLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.itemNameLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferLowercase|QtCore.Qt.InputMethodHint.ImhPreferUppercase)
        self.itemNameLineEdit.setClearButtonEnabled(True)
        self.itemNameLineEdit.setObjectName("itemNameLineEdit")
        self.itemCodeLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.itemCodeLineEdit.setGeometry(QtCore.QRect(40, 150, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.itemCodeLineEdit.setFont(font)
        self.itemCodeLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.itemCodeLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferLowercase|QtCore.Qt.InputMethodHint.ImhPreferNumbers|QtCore.Qt.InputMethodHint.ImhPreferUppercase)
        self.itemCodeLineEdit.setText("")
        self.itemCodeLineEdit.setClearButtonEnabled(True)
        self.itemCodeLineEdit.setObjectName("itemCodeLineEdit")
        self.cancelButton = QtWidgets.QPushButton(parent=self.widget)
        self.cancelButton.setGeometry(QtCore.QRect(245, 230, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(True)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("")
        self.cancelButton.setObjectName("cancelButton")
        self.containerLabel = QtWidgets.QLabel(parent=self.widget)
        self.containerLabel.setGeometry(QtCore.QRect(0, 5, 471, 301))
        self.containerLabel.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"border:3px solid #984063;")
        self.containerLabel.setText("")
        self.containerLabel.setObjectName("containerLabel")
        self.hsnLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.hsnLineEdit.setGeometry(QtCore.QRect(230, 150, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.hsnLineEdit.setFont(font)
        self.hsnLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#984063;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.hsnLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferLowercase|QtCore.Qt.InputMethodHint.ImhPreferNumbers|QtCore.Qt.InputMethodHint.ImhPreferUppercase)
        self.hsnLineEdit.setText("")
        self.hsnLineEdit.setClearButtonEnabled(True)
        self.hsnLineEdit.setObjectName("hsnLineEdit")
        self.containerLabel.raise_()
        self.removeButton.raise_()
        self.removeItemLabel.raise_()
        self.itemNameLineEdit.raise_()
        self.itemCodeLineEdit.raise_()
        self.cancelButton.raise_()
        self.hsnLineEdit.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        
        self.removeButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))
        self.cancelButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.removeButton.setText(_translate("Form", "Remove"))
        self.removeItemLabel.setText(_translate("Form", "Remove Item"))
        self.itemNameLineEdit.setPlaceholderText(_translate("Form", "Item Name*"))
        self.itemCodeLineEdit.setPlaceholderText(_translate("Form", "Item Code*"))
        self.cancelButton.setText(_translate("Form", "Cancel"))
        self.hsnLineEdit.setPlaceholderText(_translate("Form", "HSN*"))
