# Form implementation generated from reading ui file 'resetPasswordUi.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class RstPassword_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.screen = QtWidgets.QApplication.primaryScreen()
        self.screen_geometry = self.screen.geometry()
        self.screen_width = self.screen_geometry.width()
        self.screen_height = self.screen_geometry.height()
        Form.resize(self.screen_width, self.screen_height)
        Form.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(5, 5, 581, 361))
        self.widget.setStyleSheet("QPushButton#resetButton{\n"
"    background-color:#41436A;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#resetButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#F64668;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#resetButton:hover{\n"
"    background-color:#F64668;\n"
"}\n"
"QPushButton#cancelButton{\n"
"    background-color:#41436A;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#cancelButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#F64668;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#cancelButton:hover{\n"
"    background-color:#F64668;\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.usernameLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.usernameLineEdit.setGeometry(QtCore.QRect(40, 80, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.usernameLineEdit.setFont(font)
        self.usernameLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#41436A;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.usernameLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText|QtCore.Qt.InputMethodHint.ImhPreferLowercase|QtCore.Qt.InputMethodHint.ImhPreferUppercase|QtCore.Qt.InputMethodHint.ImhSensitiveData)
        self.usernameLineEdit.setText("")
        self.usernameLineEdit.setMaxLength(20)
        self.usernameLineEdit.setClearButtonEnabled(True)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.resetButton = QtWidgets.QPushButton(parent=self.widget)
        self.resetButton.setGeometry(QtCore.QRect(120, 280, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(True)
        self.resetButton.setFont(font)
        self.resetButton.setStyleSheet("")
        self.resetButton.setObjectName("resetButton")
        self.resetPasswordLabel = QtWidgets.QLabel(parent=self.widget)
        self.resetPasswordLabel.setGeometry(QtCore.QRect(20, 20, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(18)
        font.setBold(True)
        self.resetPasswordLabel.setFont(font)
        self.resetPasswordLabel.setStyleSheet("color:#41436A;")
        self.resetPasswordLabel.setObjectName("resetPasswordLabel")
        self.cancelButton = QtWidgets.QPushButton(parent=self.widget)
        self.cancelButton.setGeometry(QtCore.QRect(290, 280, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(True)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("")
        self.cancelButton.setObjectName("cancelButton")
        self.containerLabel = QtWidgets.QLabel(parent=self.widget)
        self.containerLabel.setGeometry(QtCore.QRect(0, 5, 581, 351))
        self.containerLabel.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"border:3px solid #41436A;")
        self.containerLabel.setText("")
        self.containerLabel.setObjectName("containerLabel")
        self.cnfmPasswordLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.cnfmPasswordLineEdit.setGeometry(QtCore.QRect(40, 200, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.cnfmPasswordLineEdit.setFont(font)
        self.cnfmPasswordLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#41436A;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.cnfmPasswordLineEdit.setText("")
        self.cnfmPasswordLineEdit.setMaxLength(15)
        self.cnfmPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.cnfmPasswordLineEdit.setClearButtonEnabled(True)
        self.cnfmPasswordLineEdit.setObjectName("cnfmPasswordLineEdit")
        self.passwordLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.passwordLineEdit.setGeometry(QtCore.QRect(40, 140, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#41436A;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.passwordLineEdit.setText("")
        self.passwordLineEdit.setMaxLength(15)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.passwordLineEdit.setClearButtonEnabled(True)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.containerLabel.raise_()
        self.usernameLineEdit.raise_()
        self.resetButton.raise_()
        self.resetPasswordLabel.raise_()
        self.cancelButton.raise_()
        self.cnfmPasswordLineEdit.raise_()
        self.passwordLineEdit.raise_()

        
        self.resetButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))
        self.cancelButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.usernameLineEdit.setPlaceholderText(_translate("Form", "Username*"))
        self.resetButton.setText(_translate("Form", "Reset"))
        self.resetPasswordLabel.setText(_translate("Form", "Reset Password"))
        self.cancelButton.setText(_translate("Form", "Cancel"))
        self.cnfmPasswordLineEdit.setPlaceholderText(_translate("Form", "Confirm Password*"))
        self.passwordLineEdit.setPlaceholderText(_translate("Form", "Password*"))
