# Form implementation generated from reading ui file 'signupUi.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Signup_Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        self.screen = QtWidgets.QApplication.primaryScreen()
        self.screen_geometry = self.screen.geometry()
        self.screen_width = self.screen_geometry.width()
        self.screen_height = self.screen_geometry.height()
        Form.resize(self.screen_width, self.screen_height)
        Form.setWindowFlags(QtCore.Qt.WindowType.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setGeometry(QtCore.QRect(5, 5, 581, 761))
        self.widget.setStyleSheet("QPushButton#registerButton{\n"
"    background-color:#41436A;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#registerButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#F64668;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#registerButton:hover{\n"
"    background-color:#F64668;\n"
"}\n"
"QPushButton#cancelButton{\n"
"    background-color:#41436A;\n"
"    color:rgba(255, 255, 255, 200);\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton#cancelButton:pressed{\n"
"    padding-left:5px;\n"
"    padding-top:5px;\n"
"    background-color:#F64668;\n"
"    background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#cancelButton:hover{\n"
"    background-color:#F64668;\n"
"}\n"
"QComboBox {\n"
"            border: 1px solid #41436A;\n"
"            border-radius: 5px;\n"
"            padding-left: 4px;\n"
"            padding-right: 20px; \n"
"        }\n"
"        QComboBox::drop-down {\n"
"            subcontrol-origin: padding;\n"
"            subcontrol-position: top right;\n"
"            width: 25px;\n"
"            border-left: 1px solid #41436A;\n"
"            border-top-right-radius: 5px;\n"
"            border-bottom-right-radius: 5px;\n"
"            background: #41436A;\n"
"        }\n"
"        QComboBox::down-arrow {\n"
"            border: none;\n"
"            color: white;\n"
"            padding-right: 1px;\n"
"            width: 5px;\n"
"            height: 8px;\n"
"        }\n"
"        QComboBox:on {\n"
"            border: 1px solid #26648E;\n"
"        }\n"
"        QComboBox QListView {\n"
"            border: 1px solid #984063;\n"
"            border-radius: 4px;\n"
"            padding: 5px;\n"
"            background-color: #fff;\n"
"            outline: 0px;\n"
"        }\n"
"        QComboBox QListView::item {\n"
"            padding-left: 5px;\n"
"            background-color: #fff;\n"
"        }\n"
"        QComboBox QListView::item:hover {\n"
"            background-color: #96a4c5;\n"
"        }\n"
"        QComboBox QListView::item:selected {\n"
"            background-color: #96a4c5;\n"
"        }")
        self.widget.setObjectName("widget")
        self.passwordLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.passwordLineEdit.setGeometry(QtCore.QRect(40, 520, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.passwordLineEdit.setFont(font)
        self.passwordLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#41436A;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.passwordLineEdit.setText("")
        self.passwordLineEdit.setMaxLength(15)
        self.passwordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.passwordLineEdit.setClearButtonEnabled(True)
        self.passwordLineEdit.setObjectName("passwordLineEdit")
        self.cnfmPasswordLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.cnfmPasswordLineEdit.setGeometry(QtCore.QRect(40, 590, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.cnfmPasswordLineEdit.setFont(font)
        self.cnfmPasswordLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#41436A;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.cnfmPasswordLineEdit.setText("")
        self.cnfmPasswordLineEdit.setMaxLength(15)
        self.cnfmPasswordLineEdit.setEchoMode(QtWidgets.QLineEdit.EchoMode.PasswordEchoOnEdit)
        self.cnfmPasswordLineEdit.setClearButtonEnabled(True)
        self.cnfmPasswordLineEdit.setObjectName("cnfmPasswordLineEdit")
        self.usernameLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.usernameLineEdit.setGeometry(QtCore.QRect(40, 450, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.usernameLineEdit.setFont(font)
        self.usernameLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#41436A;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.usernameLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText|QtCore.Qt.InputMethodHint.ImhPreferLowercase|QtCore.Qt.InputMethodHint.ImhPreferUppercase|QtCore.Qt.InputMethodHint.ImhSensitiveData)
        self.usernameLineEdit.setText("")
        self.usernameLineEdit.setMaxLength(20)
        self.usernameLineEdit.setClearButtonEnabled(True)
        self.usernameLineEdit.setObjectName("usernameLineEdit")
        self.registerButton = QtWidgets.QPushButton(parent=self.widget)
        self.registerButton.setGeometry(QtCore.QRect(120, 670, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(True)
        self.registerButton.setFont(font)
        self.registerButton.setStyleSheet("")
        self.registerButton.setObjectName("registerButton")
        self.signUpLabel = QtWidgets.QLabel(parent=self.widget)
        self.signUpLabel.setGeometry(QtCore.QRect(20, 30, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(18)
        font.setBold(True)
        self.signUpLabel.setFont(font)
        self.signUpLabel.setStyleSheet("color:#41436A;")
        self.signUpLabel.setObjectName("signUpLabel")
        self.nameLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.nameLineEdit.setGeometry(QtCore.QRect(40, 90, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.nameLineEdit.setFont(font)
        self.nameLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#41436A;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.nameLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhPreferLowercase|QtCore.Qt.InputMethodHint.ImhPreferUppercase)
        self.nameLineEdit.setClearButtonEnabled(True)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.roleLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.roleLineEdit.setGeometry(QtCore.QRect(330, 90, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.roleLineEdit.setFont(font)
        self.roleLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.roleLineEdit.setText("")
        self.roleLineEdit.setReadOnly(True)
        self.roleLineEdit.setObjectName("roleLineEdit")
        self.doBLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.doBLineEdit.setGeometry(QtCore.QRect(40, 160, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.doBLineEdit.setFont(font)
        self.doBLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#41436A;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.doBLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDate)
        self.doBLineEdit.setText("")
        self.doBLineEdit.setMaxLength(10)
        self.doBLineEdit.setReadOnly(True)
        self.doBLineEdit.setClearButtonEnabled(True)
        self.doBLineEdit.setObjectName("doBLineEdit")
        self.cancelButton = QtWidgets.QPushButton(parent=self.widget)
        self.cancelButton.setGeometry(QtCore.QRect(300, 670, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(True)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("")
        self.cancelButton.setObjectName("cancelButton")
        self.containerLabel = QtWidgets.QLabel(parent=self.widget)
        self.containerLabel.setGeometry(QtCore.QRect(0, 25, 581, 711))
        self.containerLabel.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border-radius:20px;\n"
"border:3px solid #41436A;")
        self.containerLabel.setText("")
        self.containerLabel.setObjectName("containerLabel")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(360, 120, 171, 231))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(8)
        self.verticalLayout.setObjectName("verticalLayout")
        self.receipientRadioButton = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(13)
        font.setBold(False)
        self.receipientRadioButton.setFont(font)
        self.receipientRadioButton.setObjectName("receipientRadioButton")
        self.verticalLayout.addWidget(self.receipientRadioButton)
        self.labTechnicianRadioButton = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(13)
        font.setBold(False)
        self.labTechnicianRadioButton.setFont(font)
        self.labTechnicianRadioButton.setObjectName("labTechnicianRadioButton")
        self.verticalLayout.addWidget(self.labTechnicianRadioButton)
        self.technicalManagerRadioButton = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(13)
        font.setBold(False)
        self.technicalManagerRadioButton.setFont(font)
        self.technicalManagerRadioButton.setObjectName("technicalManagerRadioButton")
        self.verticalLayout.addWidget(self.technicalManagerRadioButton)
        self.accountManagerRadioButton = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(13)
        font.setBold(False)
        self.accountManagerRadioButton.setFont(font)
        self.accountManagerRadioButton.setObjectName("accountManagerRadioButton")
        self.verticalLayout.addWidget(self.accountManagerRadioButton)
        self.adminRadioButton = QtWidgets.QRadioButton(parent=self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(13)
        font.setBold(False)
        self.adminRadioButton.setFont(font)
        self.adminRadioButton.setObjectName("adminRadioButton")
        self.verticalLayout.addWidget(self.adminRadioButton)
        self.MnoLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.MnoLineEdit.setGeometry(QtCore.QRect(40, 310, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.MnoLineEdit.setFont(font)
        self.MnoLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#41436A;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.MnoLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.MnoLineEdit.setText("")
        self.MnoLineEdit.setMaxLength(10)
        self.MnoLineEdit.setClearButtonEnabled(True)
        self.MnoLineEdit.setObjectName("MnoLineEdit")
        self.addressLineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.addressLineEdit.setGeometry(QtCore.QRect(40, 380, 491, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        font.setBold(False)
        self.addressLineEdit.setFont(font)
        self.addressLineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"border-bottom-color:#41436A;\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:7px;")
        self.addressLineEdit.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly|QtCore.Qt.InputMethodHint.ImhPreferLowercase|QtCore.Qt.InputMethodHint.ImhPreferUppercase)
        self.addressLineEdit.setText("")
        self.addressLineEdit.setMaxLength(60)
        self.addressLineEdit.setClearButtonEnabled(True)
        self.addressLineEdit.setObjectName("addressLineEdit")
        self.genderComboBox = QtWidgets.QComboBox(parent=self.widget)
        self.genderComboBox.setGeometry(QtCore.QRect(40, 240, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        self.genderComboBox.setFont(font)
        self.genderComboBox.setCurrentText("")
        self.genderComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.SizeAdjustPolicy.AdjustToContentsOnFirstShow)
        self.genderComboBox.setPlaceholderText("Gender")
        self.genderComboBox.setObjectName("genderComboBox")
        self.genderComboBox.addItem("")
        self.genderComboBox.addItem("")
        self.genderComboBox.addItem("")
        self.DoBDateEdit = QtWidgets.QDateEdit(parent=self.widget)
        self.DoBDateEdit.setGeometry(QtCore.QRect(110, 160, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Dubai")
        font.setPointSize(14)
        self.DoBDateEdit.setFont(font)
        self.DoBDateEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0);\n"
"border:2px solid rgba(0, 0, 0, 0);\n"
"color:rgb(0, 0, 0);\n"
"padding-bottom:5px;")
        self.DoBDateEdit.setCalendarPopup(False)
        self.DoBDateEdit.setObjectName("DoBDateEdit")
        self.containerLabel.raise_()
        self.passwordLineEdit.raise_()
        self.cnfmPasswordLineEdit.raise_()
        self.usernameLineEdit.raise_()
        self.registerButton.raise_()
        self.signUpLabel.raise_()
        self.nameLineEdit.raise_()
        self.roleLineEdit.raise_()
        self.doBLineEdit.raise_()
        self.cancelButton.raise_()
        self.horizontalLayoutWidget.raise_()
        self.MnoLineEdit.raise_()
        self.addressLineEdit.raise_()
        self.genderComboBox.raise_()
        self.DoBDateEdit.raise_()

        
        self.registerButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))
        self.cancelButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25,xOffset=3,yOffset=3))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.passwordLineEdit.setPlaceholderText(_translate("Form", "Password*"))
        self.cnfmPasswordLineEdit.setPlaceholderText(_translate("Form", "Confirm Password*"))
        self.usernameLineEdit.setPlaceholderText(_translate("Form", "Username*"))
        self.registerButton.setText(_translate("Form", "Register"))
        self.signUpLabel.setText(_translate("Form", "Sign Up"))
        self.nameLineEdit.setPlaceholderText(_translate("Form", "Name*"))
        self.roleLineEdit.setPlaceholderText(_translate("Form", "Role*"))
        self.doBLineEdit.setPlaceholderText(_translate("Form", "DoB*"))
        self.cancelButton.setText(_translate("Form", "Cancel"))
        self.receipientRadioButton.setText(_translate("Form", "Receipient"))
        self.labTechnicianRadioButton.setText(_translate("Form", "Lab Technician"))
        self.technicalManagerRadioButton.setText(_translate("Form", "Technical Manager"))
        self.accountManagerRadioButton.setText(_translate("Form", "Account Manager"))
        self.adminRadioButton.setText(_translate("Form", "Admin"))
        self.MnoLineEdit.setPlaceholderText(_translate("Form", "Mobile number*"))
        self.addressLineEdit.setPlaceholderText(_translate("Form", "Address*"))
        self.genderComboBox.setPlaceholderText(_translate("Form", "Gender*"))
        self.genderComboBox.setItemText(0, _translate("Form", "Female"))
        self.genderComboBox.setItemText(1, _translate("Form", "Male"))
        self.genderComboBox.setItemText(2, _translate("Form", "Other"))
        self.DoBDateEdit.setSpecialValueText(_translate("Form", "Exp. Date*"))
        self.DoBDateEdit.setDisplayFormat(_translate("Form", "yyyy-MM-dd"))
